# Build CFP Notification Job
# https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets

name: CI

env:
  PINBOARD_TOKEN: ${{ secrets.PINBOARD_TOKEN }}
  ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME  }}
  ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD  }}
  CF_API: ${{ secrets.CF_API  }}
  CF_PASSWORD: ${{ secrets.CF_PASSWORD  }}
  CF_USER: ${{ secrets.CF_USER  }}
  CF_SPACE: ${{ secrets.CF_SPACE  }}
  CF_ORG: ${{ secrets.CF_ORG  }}
  AWS_REGION: ${{ secrets.AWS_REGION  }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID  }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID  }}
  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY  }}
  CFP_NOTIFICATIONS_FUNCTION_NAME: ${{ secrets.CFP_NOTIFICATIONS_FUNCTION_NAME  }}
  CFP_NOTIFICATIONS_FUNCTIONNAME: ${{ secrets.CFP_NOTIFICATIONS_FUNCTIONNAME  }}
  CFP_NOTIFICATIONS_DESTINATION_EMAIL: ${{ secrets.CFP_NOTIFICATIONS_DESTINATION_EMAIL  }}
  CFP_NOTIFICATIONS_DESTINATION_NAME: ${{ secrets.CFP_NOTIFICATIONS_DESTINATION_NAME  }}
  CFP_NOTIFICATIONS_SOURCE_EMAIL: ${{ secrets.CFP_NOTIFICATIONS_SOURCE_EMAIL  }}
  CFP_NOTIFICATIONS_SOURCE_NAME: ${{ secrets.CFP_NOTIFICATIONS_SOURCE_NAME  }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B deploy --file pom.xml

      - name: Deploy to Cloud Foundry
        run: |
          cd $GITHUB_WORKSPACE
          ./deploy/cf.sh
          ./deploy/deploy.sh